services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.local
    container_name: transcode-api-local
    ports:
      - "8087:8087"
    environment:
      # Database Configuration - using existing server
      - DATABASE_URL=postgresql+asyncpg://transcode_user:transcode_pass@192.168.0.234:5433/transcode_db
      
      
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8087
      - DEBUG=true

      # Performance optimizations
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONHASHSEED=random
      
      # Local development - no GPU/cloud services
      - FFMPEG_HWACCEL=none
      - FFMPEG_GPU_ENABLED=false
      
      # Shared Volume Configuration
      - SHARED_VOLUME_PATH=/shared/media
      
      # AWS S3 Configuration (optional for local)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-}
      - AWS_ENDPOINT_PUBLIC_URL=${AWS_ENDPOINT_PUBLIC_URL:-}
      - AWS_BASE_FOLDER=${AWS_BASE_FOLDER:-}
      
      # Google Cloud credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      
      # PubSub Configuration
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID:-}
      - PUBSUB_TASKS_TOPIC=${PUBSUB_TASKS_TOPIC:-}
      - TASKS_SUBSCRIPTION=${TASKS_SUBSCRIPTION:-}
      - PUBSUB_RESULTS_TOPIC=${PUBSUB_RESULTS_TOPIC:-}
      - PUBSUB_RESULTS_SUBSCRIPTION=${PUBSUB_RESULTS_SUBSCRIPTION:-}
      - PUBSUB_PUBLISHER_CREDENTIALS_PATH=/app/key.json
      - PUBSUB_SUBSCRIBER_CREDENTIALS_PATH=/app/key.json
      - DISABLE_PUBSUB=${DISABLE_PUBSUB:-false}
      
      # Face Detection Pub/Sub Configuration
      - PUBSUB_FACE_DETECTION_TASKS_TOPIC=${PUBSUB_FACE_DETECTION_TASKS_TOPIC:-}
      - PUBSUB_FACE_DETECTION_RESULTS_TOPIC=${PUBSUB_FACE_DETECTION_RESULTS_TOPIC:-}
      
    volumes:
      - /tmp/transcode:/tmp/transcode
      - ../src/transcode_service/key.json:/app/key.json:ro
      - shared-media:/shared/media     # Shared volume for downloaded media files
    restart: always
    # Health check
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8087/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

  consumer:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.local
    container_name: transcode-consumer-local
    command: [ "python", "-m", "transcode_service.workers.transcode_worker" ]
    environment:
      # Database Configuration - using existing server
      - DATABASE_URL=postgresql+asyncpg://transcode_user:transcode_pass@192.168.0.234:5433/transcode_db
      
      
      # Worker Configuration
      - WORKER_CONCURRENCY=2
      
      # Performance optimizations
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      
      # Local development - CPU only
      - FFMPEG_HWACCEL=none
      - FFMPEG_GPU_ENABLED=false
      
      # Shared Volume Configuration
      - SHARED_VOLUME_PATH=/shared/media
      
      # AWS S3 Configuration (optional for local)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-}
      - AWS_ENDPOINT_PUBLIC_URL=${AWS_ENDPOINT_PUBLIC_URL:-}
      - AWS_BASE_FOLDER=${AWS_BASE_FOLDER:-}
      
      # Google Cloud credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      
      # PubSub Configuration
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID:-}
      - PUBSUB_TASKS_TOPIC=${PUBSUB_TASKS_TOPIC:-}
      - PUBSUB_PUBLISHER_CREDENTIALS_PATH=/app/key.json
      - PUBSUB_SUBSCRIBER_CREDENTIALS_PATH=/app/key.json
      - DISABLE_PUBSUB=${DISABLE_PUBSUB:-false}
      
    volumes:
      - ./logs:/app/logs
      - /tmp/transcode:/tmp/transcode
      - ../src/transcode_service/key.json:/app/key.json:ro
      - shared-media:/shared/media     # Shared volume for downloaded media files
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'

  face-detection-worker:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.local
    container_name: transcode-face-detection-worker-local
    command: [ "python", "-m", "transcode_service.workers.face_detect_worker" ]
    environment:
      # Database Configuration - using existing server
      - DATABASE_URL=postgresql+asyncpg://transcode_user:transcode_pass@192.168.0.234:5433/transcode_db
      
      
      # Performance optimizations
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONHASHSEED=random
      
      # AWS S3 Configuration (optional for local)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-}
      - AWS_ENDPOINT_PUBLIC_URL=${AWS_ENDPOINT_PUBLIC_URL:-}
      - AWS_BASE_FOLDER=${AWS_BASE_FOLDER:-}
      
      # Google Cloud credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      
      # Disable GPU for local development, but enable PubSub with credentials
      - NVIDIA_VISIBLE_DEVICES=
      - NVIDIA_DRIVER_CAPABILITIES=
      
      # Shared Volume Configuration
      - SHARED_VOLUME_PATH=/shared/media
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID:-}
      - PUBSUB_FACE_DETECTION_TASKS_TOPIC=${PUBSUB_FACE_DETECTION_TASKS_TOPIC:-}
      - PUBSUB_FACE_DETECTION_RESULTS_TOPIC=${PUBSUB_FACE_DETECTION_RESULTS_TOPIC:-}
      - PUBSUB_PUBLISHER_CREDENTIALS_PATH=/app/key.json
      - PUBSUB_SUBSCRIBER_CREDENTIALS_PATH=/app/key.json
      - FACE_DETECTION_SUBSCRIPTION=${FACE_DETECTION_SUBSCRIPTION:-}
      - ORT_LOGGING_LEVEL=4
      - DISABLE_PUBSUB=${DISABLE_PUBSUB:-false}
      
    volumes:
      - ./logs:/app/logs
      - ./models_faces:/app/models_faces
      - /tmp/transcode:/tmp/transcode
      - ../src/transcode_service/key.json:/app/key.json:ro
      - shared-media:/shared/media     # Shared volume for downloaded media files
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

  task-listener:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.local
    container_name: transcode-task-listener-local
    command: [ "python", "-m", "transcode_service.workers.task_listener" ]
    environment:
      # Database Configuration - using existing server
      - DATABASE_URL=postgresql+asyncpg://transcode_user:transcode_pass@192.168.0.234:5433/transcode_db
      
      
      # Performance optimizations
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONHASHSEED=random
      
      # AWS S3 Configuration (optional for local)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-}
      - AWS_ENDPOINT_PUBLIC_URL=${AWS_ENDPOINT_PUBLIC_URL:-}
      - AWS_BASE_FOLDER=${AWS_BASE_FOLDER:-}
      
      # Google Cloud credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      
      # PubSub Configuration for task listener
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID:-}
      - PUBSUB_TASKS_TOPIC=${PUBSUB_TASKS_TOPIC:-}
      - PUBSUB_RESULTS_TOPIC=${PUBSUB_RESULTS_TOPIC:-}
      - PUBSUB_PUBLISHER_CREDENTIALS_PATH=/app/key.json
      - PUBSUB_SUBSCRIBER_CREDENTIALS_PATH=/app/key.json
      - PUBSUB_TASK_SUBSCRIPTION=${PUBSUB_TASK_SUBSCRIPTION:-}
      - PUBSUB_MAX_MESSAGES=5
      - DISABLE_PUBSUB=${DISABLE_PUBSUB:-false}
      
    volumes:
      - ./logs:/app/logs
      - ../src/transcode_service/key.json:/app/key.json:ro
      - shared-media:/shared/media     # Shared volume for downloaded media files
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: transcode-frontend-local
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'

volumes:
  shared-media:
    driver: local

